logging:
  level:
    root: INFO
    transportation: DEBUG

server:
  port: 8082

services:
#  if you need to go to another services

spring:
  datasource:
    password: 123
    username: postgres
    url: jdbc:postgresql://localhost:5432/
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        show_sql: false
        format_sql: false
        use_sql_comments: false
    hibernate:
      ddl-auto: none
    generate-ddl: true
