spring:
  application:
    name: transportation-user-service
    liquibase:
      changeLog:
      enabled: true

springdoc:
  swagger-ui:
    doc-expansion: none
    default-model-rendering: model

management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: true
    web.exposure.include: '*'
  endpoint:
    info.enabled: true
    health:
      enabled: true
      show-details: always
    loggers.enabled: true